name: CI - Fábrica de Desarrolladores

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout del código
        uses: actions/checkout@v3

      - name: 🟦 Instalar dependencias
        run: npm install

      - name: 🧪 Ejecutar pruebas simuladas
        run: echo "Simulando pruebas exitosas" && exit 0
